version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: rideboard
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: rideboard
    volumes:
      - ./src/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
